### ISSUE TITLE
Is it support ticketing system?

### ISSUE THREAD

**Issue by ugintl** [krystalcode/drupal7-bonsai#1]
I am a little confused. Is it a support ticketing system? What is bonsai?

**Comment by krystalcode** [comment]
@ugintl Apologies for the delayed response, I missed the notification and did not see your message earlier. At this point it is simply a system to send and receive email messages via Mailgun. Emails (sent and received) are stored as nodes in Drupal. This opens up a lot of possibilities that go beyond traditional email clients. The bigger idea (should it undergo further development) is to develop features in 2 areas:

- Email management system for projects/companies; for example using groups (via OG in Drupal 7) allow many users to have access to the same email address, while taking advantage of a strong access control system; allowing comments (internal to the project/company) on emails (already possible).
- Support ticketing system.

Note that the project is just maintained at the moment, even though I do use it and plan to take it further at some point, most likely with a Drupal 8 version.
